### ISSUE TITLE
Design, Metrics and configuration

### ISSUE THREAD

**Issue by joente** [oversight/nmapprobe#1]
**Is your feature request related to a problem? Please describe.**
We have to decide which metrics need to be collected and which configuration options must be available

**Describe the solution you'd like**

Looking at the "old" probe, a lot of the code can be re-used. The use of ET (`ElementTree`) is correct as `nmap` can return data using XML. As sub-processes are used to gather the data, it should not be required to use a Thread-pool. I can't find a reason to use threads for each call so better change that code into a [Semaphore](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Semaphore).

The "OS" and "TraceRoute" checks can be removed, which leaves two checks, *checkCertificates* and *checkServices*. (Note that checkCertificates is singular in the "old" probe, we want to change this into plural as it is plural, multiple ports are checked)

**Config:**

- `ip4`: str (hostname)
- `checkCertificatePorts` : List of ports to perform certificates check on. If this list is empty, we should not run the check as no port to check is available. Default: 443,995,993,465,3389,989,990,636,5986. The result should only contain the ports which have a result.
- `checkPorts` : List of ports to perform check on. If this list is empty, we should not run the check as no port to check is available. Default: - (empty). The result should contain the result for all given ports, thus also include "closed" ports.

checkCertificatePorts: (443,995,993,465,3389,989,990,636,5986 is the default)
```
nmap --script +ssl-cert,+ssl-enum-ciphers -oX - -p 443,995,993,465,3389,989,990,636,5986 <HOST>
```

checkPorts: (80,8080,5000 is an example)
```
nmap --max-rtt-timeout 750ms --min-rtt-timeout 50ms --initial-rtt-timeout 80ms --host-timeout 10s --max-retries 2 --max-scan-delay 3ms --version-intensity 5 -oX - -p 80,8080,5000 <HOST>
```

**Checks:**

**checkCertificates**

Types:
- *sslCert*
- *sslEnumCiphers*

Type `sslCert`:
- `name`: `f'{address}:{port}'`, string, for example: "192.168.21.10:3389"
- `subject`: string, (calculate as before)
- `issuer`: string, (calculate as before)
- `validNotBefore`: (int) as timestamp
- `validNotAfter`: (int) as timestamp
- `isValid`: boolean (true if withing valid window, both before and after)
- `expiresIn`: int, number of seconds until `validNotAfter is reached. (negative value after validNotAfter)
- `pubkeyType`:  string, (calculate as before)
- `pubkeyBits`:  string, (calculate as before)
- `md5`:  string, (calculate as before)
- `sha1`:  string, (calculate as before)

Type `sslEnumCiphers`:
All the metrics as before except `least_strength` must be `leastStrength`.

**checkPorts**

Types:
- *port*

Metrics:
- `name`: `f'{protocol}:{portid}'` , str, for example: "tcp:80"
- `state`: string,, for example: "closed"
- `reason`: string, for example: "conn-refused" 
~- `reason_ttl`: int, for example 0~
- `reasonTTL`: int, for example 0

**Comment by riklempens** [comment]
Closing as we released this already as tcpprobe
